version: "3"
services:
  springboot-app:
    container_name: spring-boot-docker
    image: haithem2301/spring-boot-docker
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - ./my-datavolume:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: devops
      MYSQL_ROOT_PASSWORD: root
  frontend:
    image: haithem2301/angular-app:latest
    container_name: angular
    ports:
      - "4200:4200"
    restart: unless-stopped
    depends_on:
      - springboot-app


