version: "3"
services:
  springboot-app:
    container_name: spring-boot-docker
    image: haithem2301/spring-boot-docker:latest
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
    networks:
      - dev-net
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    volumes:
      - ./my-datavolume:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: devops
      MYSQL_ROOT_PASSWORD: root
  frontend:
    image: haithem2301/angular-app:latest
    container_name: angular
    volumes: # Volume binding
      - './angulardockerproject:/usr/src/app'
    command: >
      bash -c "npm install && ng serve --host 0.0.0.0 --port 4200"
    ports:
      - 4200:4200
    restart: unless-stopped
    depends_on:
      - springboot-app
    networks:
      - dev-net
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/var/lib/jenkins/workspace/DevOpsBackend/prometheus
    networks:
      - dev-net
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/jenkins/workspace/DevOpsBackend/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=haithem
    depends_on:
      - prometheus
    networks:
      - dev-net

networks:
  dev-net:


