version: "3"
services:
  springboot-app:
    container_name: DevOps_Project
    image: haithem2301/spring-boot-docker
    restart: always
    build: .
    ports:
      - 8081:8080
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldb
    image: mysql
    volumes:
      - ./my-datavolume:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: devops
      MYSQL_ROOT_PASSWORD: root